---
- hosts: all
  become: true 
  tasks:
    - name: Update apt cache
      apt: 
        update_cache: yes

    - name: Upgrade packages
      apt: 
        upgrade: dist
      
    - name: Install any pending upgrades
      apt: 
        upgrade: yes
